// Source: lava-ice-logs/2026-04-29/agent-harness-pre-execution-understanding-gate-architecture.md §7.2
export const FAST_CONFIRM_PROMPT = `# Fast Confirm Mode

Before executing, provide a short confirmation summary:

- I understood the task as: ...
- I will do: ...
- I will not touch: ...
- I will verify by: ...
- Assumptions: ...

Do not start execution until confirmed.`;
