// Fast-confirm mode prompt: the pre-execution understanding-gate architecture design.
export const FAST_CONFIRM_PROMPT = `# Fast Confirm Mode

Before executing, provide a short confirmation summary:

- I understood the task as: ...
- I will do: ...
- I will not touch: ...
- I will verify by: ...
- Assumptions: ...

Do not start execution until confirmed.`;
